### ISSUE TITLE
Science Direct scraper fails

### ISSUE THREAD

**Issue by robintw** [ContentMine/journal-scrapers#43]
I'm trying to run the science_direct scraper from the `non-open` branch. When running:

`quickscrape --url http://dx.doi.org/10.1016/j.rse.2015.10.005 --scraper /Users/robin/code/journal-scrapers/scrapers/science_direct.json --output .`

I get the following error:

```
info: quickscrape 0.4.7 launched with...
info: - URL: http://dx.doi.org/10.1016/j.rse.2015.10.005
info: - Scraper: /Users/robin/code/journal-scrapers/scrapers/science_direct.json
info: - Rate limit: 3 per minute
info: - Log level: info
info: urls to scrape: 1
info: processing URL: http://dx.doi.org/10.1016/j.rse.2015.10.005
info: [scraper]. URL rendered. http://www.sciencedirect.com/science/article/pii/S0034425715301565?via%3Dihub.
info: [scraper]. download started. science.
/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:221
  for (var key in obj) {
           ^

RangeError: Maximum call stack size exceeded
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:221:12)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
    at fillChildResults (/usr/local/lib/node_modules/quickscrape/node_modules/thresher/lib/scraper.js:233:5)
```

It seems like there is some sort of infinite recursion going on in the `thresher` library.

Any ideas?

**Comment by chartgerink** [comment]
You could try using this elsevier scraping definition from my fork.
https://github.com/chartgerink/journal-scrapers/blob/master/scrapers/elsevier.json

**Comment by rossmounce** [comment]
Issue resolved by using chartgerink's elsevier.json which is now the default for elsevier. The old science_direct.json has already been removed/deleted
